### ISSUE TITLE
Logo design proposal

### ISSUE THREAD

**Issue by teneresa** [Trilarion/coloring#17]
Hi, my name is Valeria. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon design for your app. If it's something you're interested in, please, let me know!
Best,
Valeria

**Comment by Trilarion** [comment]
Hi Valeria,

Thanks for your generous offer. Yes, I would be interested in that.

**Comment by teneresa** [comment]
Glad to hear this! Do you have any special requirements for the logo - any symbol or text to be included in it?

**Comment by Trilarion** [comment]
No special requirements. The app is aimed at kids and adults alike. The topic is coloring. At some point I would probably have tried to put a box of colored pencils as logo, but this is what almost everyone does.

Technically, I prefer a scalable vector format like SVG over rasterized images and it would be kind of you could release your work under a license like cc-by-sa but at least your permission to use your work in this project is needed.

I'm curious what you will come up with. Thanks again for the offer.

**Comment by teneresa** [comment]
Hi, here are some options. Please let me know if you like anyone. As for the license, it could be Creative Commons license and you can use the logo everywhere you want :) 
![coloring-01](https://user-images.githubusercontent.com/39339824/43671476-3812c3b8-9771-11e8-8d60-039bc052db47.jpg)

**Comment by Trilarion** [comment]
That looks great, especially no. 3. From the castles I like 2 more than 1. I would go for 3.

**Comment by teneresa** [comment]
Yes, thanks! I think it's nice and more suitable for a kids app :)
Here are some color schemes, please select the one you like most. And I also prepared monochrome options in case they are required.
![coloring-02](https://user-images.githubusercontent.com/39339824/43679531-d9c526b6-97fc-11e8-9dd0-8902c19ca85e.jpg)

**Comment by Trilarion** [comment]
I like 3 most. It has a light background and a bright color of the pen. Monochrome versions may come in handy. The left monochrome version looks very clear.

**Comment by teneresa** [comment]
Ok, I'll prepare all the required files with the 3rd version and create a pull-request.

**Comment by teneresa** [comment]
I uploaded the files. The folder includes PNG, SVG, PSD and vector source file with all the options, so you can create any other format if requires. Or I can create it myself and you'll be able to download it from my Google drive :)

**Comment by Trilarion** [comment]
Many thanks for your nice work. I will merge your addition tomorrow. One last detail: How do you want to be called as contributor?

**Comment by teneresa** [comment]
You can use my nic Teneresa, thanks!

**Comment by Trilarion** [comment]
I included your logo. Thanks again and all the best!
